---
title: "1st Year Project"
author: "Mengzhe Wei"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: journal
    toc: yes
    toc_float:
      collapsed: true
---

# 1st Year Project Analyses

## Setting up dataset
```{r setup1, eval=T, include=FALSE, warning=F, message=F, cache=F}
rm(list=ls());

#Load Packages
library(tidyverse);library(psych);library(lme4); library(lmerTest); library(performance); library(car) ; library(yarrr)#load package

#Load Data
data.in.path <- "C:/Users/11091/OneDrive - University of Southern California/Research/CARLab/data/Mengzhe/" #path for data

demo <-  read.csv(paste0(data.in.path, "demo.csv"))
EMA <-  read.csv(paste0(data.in.path, "CARS_pr_pst_EMA.csv"))
redcap.desi <- read.csv(paste0(data.in.path, "sites_merged_alldata.csv"))
flanker <- read.csv(paste0(data.in.path, "compiled-flanker-data.csv"))
setshift <- read.csv(paste0(data.in.path, "compiled-setshift-data.csv"))
PGNG <- read.csv(paste0(data.in.path, "CAR_PGNG_index.csv"))
nback <-  read.csv(paste0(data.in.path, "compiled-nback-data.csv"))
instability <- read.csv(paste0(data.in.path, "CAR_EMA_affect_fluctuaction_var_by_ID.csv"))

#Clean up PID, make it all the same format
EMA$PID <- gsub("\\.0$", "", EMA$record_id_x)  # remove trailing ".0"
EMA$PID <- gsub("[A-Za-z]$", "", EMA$PID)      # remove trailing letters
redcap.desi$PID <- gsub("[A-Za-z]$", "", redcap.desi$participant_id)
demo$PID <- as.factor(demo$PID);
EMA$PID <- as.factor(EMA$PID);
redcap.desi$PID <- as.factor(redcap.desi$PID);
PGNG$PID <- as.factor(PGNG$subjectid);
flanker$PID <- as.factor(flanker$subject_id);
nback$PID <-as.factor(nback$subject_id);
setshift$PID <-as.factor(setshift$subject_id);  
instability$PID <- as.factor(instability$record_id)

#Only include the PIDs that are in the demo
redcap.desi.clean <- redcap.desi[redcap.desi$PID %in% demo$PID,]
flanker.clean <- flanker[flanker$PID %in% demo$PID,] 
setshift.clean <- setshift[setshift$PID %in% demo$PID,]
nback.clean <- nback[nback$PID %in% demo$PID,]

#Drop unused levels
redcap.desi.clean$PID <- droplevels(redcap.desi.clean$PID)
flanker.clean$PID <- droplevels(flanker.clean$PID)
setshift.clean$PID <- droplevels(setshift.clean$PID)
nback.clean$PID <- droplevels(nback.clean$PID)
```

```{r datastr, eval=T, include=FALSE, warning=F, message=F, cache=F}
#clean up demo data
demo.clean<- demo %>%
  mutate(
    Race = trimws(Race),
    Race = case_when(
      Race %in% c("", NA,  "Unknown or not reported") ~ "Unknown or not reported",
      Race %in% c("Black", "Black or African American", "Black/African American") ~ "Black/African American",
      Race %in% c("More Than One Race", "More than one race", "Asain and White") ~ "More Than One Race",
      TRUE ~ Race),
    Ethnicity = trimws(Ethnicity),
    Ethnicity = case_when(
      Ethnicity %in% c("", NA) ~ "Unknown or not reported",
      Ethnicity %in% c("Hispanic or Latinx", "Hispanic/Latino") ~ "Hispanic/Latinx",
      Ethnicity %in% c("Not Hispanic or Latinx", "Not Hispanic/Latino", "Not Hispanic/Latinx") ~ "Not Hispanic/Latinx",
      TRUE ~ Ethnicity))

#sers_reappraisal_pst: I reminded myself that difficult feelings won't last [This is coded as ER]
#dec_unpleasant_pst: I could observe unpleasant feelings without being drawn into them [This this de-centering, not coded as ER]
#dec_separate_pst: I could separate myself from my thoughts and feelings) as regulation [This this de-centering, not coded as ER]
#ER coding: 0-10; 0 is NA, 1 is not at all.
EMA.clean <- EMA %>%
  mutate(
    ER_yes = if_else(
      rowSums(across(
        c(seri_distraction_pst, seri_reappraisal_pst, seri_acceptance_pst,
          seri_distraction2_pst, seri_reappraisal2_pst, seri_acceptance2_pst,
          sers_reappraisal_pst),
        ~ .x >= 2 & .x <= 10,
        .names = "flag_{col}"
      ), na.rm = TRUE) > 0,
      1, 0), 
    PA_pre = rowMeans(across(c(relaxed_pre, cheerful_pre, confident_pre, accepted_pre, happy_pre)),
                      na.rm = TRUE),
    NA_pre = rowMeans(across(c(sad_pre, frustrated_pre, angry_pre, stressed_pre, irritable_pre)),
                      na.rm = TRUE),
    PA_pst = rowMeans(across(c(relaxed_pst, cheerful_pst, confident_pst, accepted_pst, happy_pst)),
                      na.rm = TRUE),
    NA_pst = rowMeans(across(c(sad_pst, frustrated_pst, angry_pst, stressed_pst, irritable_pst)),
                      na.rm = TRUE),
    PA_change_raw = PA_pst - PA_pre,
    NA_change_raw = NA_pst - NA_pre,
    perceived_success = na_if(sers_success_pst, 0),  #0 is not applicable
    perceived_success_gmc = scale(perceived_success, center = T, scale = F), #grand-mean centering
    PA_avg = rowMeans(across(c("PA_pre", "PA_pst")), na.rm = TRUE),
    NA_avg = rowMeans(across(c("NA_pre", "NA_pst")), na.rm = TRUE),
    PA_gmc = scale(PA_avg, center = T, scale = F),
    NA_gmc = scale(NA_avg, center = T, scale = F),
  ) %>%
  group_by(PID) %>%
  mutate(
    perceived_success_w = perceived_success - mean(perceived_success,na.rm=TRUE), #person-mean deviation: within-person variation
    perceived_success_b = perceived_success_gmc - perceived_success_w,
    PA_pre_w = PA_pre - mean(PA_pre,na.rm=TRUE),
    NA_pre_w = NA_pre - mean(NA_pre,na.rm=TRUE),
    PA_w = PA_avg - mean(PA_avg,na.rm=TRUE),
    NA_w = NA_avg - mean(NA_avg,na.rm=TRUE),
    PA_b = PA_gmc - PA_w,
    NA_b = NA_gmc - NA_w
  ) %>%
  ungroup()

#Participants regulated around 48% of the prompts
table(EMA.clean$ER_yes)
prop.table(table(EMA.clean$ER_yes))
#There are 1851 post survey prompts that are completed
table(EMA.clean$pst_complete)

#Affect variability
affect_sd <- EMA.clean %>%
  group_by(PID) %>%
  summarise(
    NA_mean_pre = mean(NA_pre, na.rm = TRUE),
    NA_mean_pst = mean(NA_pst, na.rm = TRUE),
    PA_mean_pre = mean(PA_pre, na.rm = TRUE),
    PA_mean_pst = mean(PA_pst, na.rm = TRUE),
    NA_mean_merged =  mean(c(NA_pre, NA_pst), na.rm = TRUE),
    PA_mean_merged =  mean(c(PA_pre, PA_pst), na.rm = TRUE),
    NA_sd_pre = sd(NA_pre, na.rm = TRUE),
    NA_sd_pst = sd(NA_pst, na.rm = TRUE),
    NA_sd_merged = sd(c(NA_pre, NA_pst), na.rm = TRUE),
    PA_sd_pre = sd(PA_pre, na.rm = TRUE),
    PA_sd_pst = sd(PA_pst, na.rm = TRUE),
    PA_sd_merged = sd(c(PA_pre, PA_pst), na.rm = TRUE),
    .groups = "drop"
  )

#Create a data set where participants indicated regulation
EMA.ERonly <- EMA.clean %>%
  filter(ER_yes == 1) %>%
  group_by(PID) %>%
  mutate(
    PA_change_raw_pm = mean(PA_change_raw, na.rm = TRUE),
    NA_change_raw_pm = mean(NA_change_raw, na.rm = TRUE)
  ) %>% # Mean level of NA and PA change raw score among the regulated prompts [just to check distribution]
  ungroup()

#Create a data set where participants did not indicate regulation
EMA.NoER <- EMA.clean %>%
  filter(ER_yes == 0)

BDI.followup <- redcap.desi.clean %>%
  filter(redcap_event_name == "visit_4_arm_1")%>%
  select(PID, bdi_score) %>%
  mutate(bdi_followup = bdi_score)

redcap.v1 <- redcap.desi.clean %>%
  filter(redcap_event_name == "visit_1a_arm_1") %>%
  select(PID, bdi_score, pswq_total,eri_pu_total, eri_rrf_total, eri_ftaf_total,eri_gen_total, eri_ecw_total,
          ham_a_score,
          hamd_sf_total) %>%
  mutate(bdi_gmc = scale(bdi_score, center = T, scale = F))

trait.level <- demo.clean %>% 
  left_join(flanker.clean %>% select(PID, flanker_score) %>% mutate(flanker_gmc = scale(flanker_score, center = T, scale = F)), by = c("PID" = "PID")) %>%
  left_join(setshift.clean %>% select(PID, shift_score) %>% mutate(shift_gmc = scale(shift_score, center = T, scale = F)), by = c("PID" = "PID")) %>%
  left_join(nback.clean %>%
    select(PID, nb1_score, nb2_score) %>%
    mutate(
      nback_score = rowMeans(cbind(nb1_score, nb2_score), na.rm = TRUE),
      nback_gmc = scale(nback_score, center = TRUE, scale = FALSE)
    ), by = "PID") %>%
  left_join(affect_sd, by = c("PID" = "PID")) %>%
  left_join (BDI.followup %>% select(PID, bdi_followup), by = c("PID" = "PID")) %>%
  left_join (redcap.v1, by = c("PID" = "PID")) %>%
  left_join(instability %>% select(PID, RMSSD_NA, RMSSD_PA), by = c("PID" = "PID")) %>%
  left_join(EMA.clean %>% group_by(PID) %>%
              summarise(
                PA_b = unique(PA_b)[1],
                NA_b = unique(NA_b)[1],
                .groups = "drop"
              ),
            by = "PID") %>%
  left_join(PGNG %>% select(PID, PCI_Avg_Cleaned,RT_Avg_Cleaned) %>% mutate(PCI_gmc = scale (PCI_Avg_Cleaned, center = T, scale = F), RT_gmc =  scale (RT_Avg_Cleaned, center = T, scale = F), by = "PID"))

EMA.ERonly <- EMA.ERonly %>% left_join(trait.level %>% select(-PA_b, -NA_b), by = "PID")
EMA.all <- EMA.clean %>% left_join(trait.level %>% select(-PA_b, -NA_b), by = "PID")
EMA.NoER <-EMA.NoER %>% left_join(trait.level %>% select(-PA_b, -NA_b), by = "PID")
```

```{r demo, eval=T, echo=T, warning=F, message=F, cache=F}
demo.clean %>%
  group_by(Group) %>%
  summarise(
    total_count = n(),
    perc = 100 * n() / nrow(demo.clean)
  )
demo.clean %>%
  group_by(Gender) %>%
  summarise(
    total_count = n(),
    perc = 100 * n() / nrow(demo.clean)
  )
describe(demo.clean$Age)
demo.clean %>%
  group_by(Race) %>%
  summarise(
    total_count = n(),
    perc = 100 * n() / nrow(demo.clean)
  )
demo.clean %>%
  group_by(Ethnicity) %>%
  summarise(
    total_count = n(),
    perc = 100 * n() / nrow(demo.clean)
  )
demo.clean %>%
  group_by(Site) %>%
  summarise(
    total_count = n(),
    perc = 100 * n() / nrow(demo.clean)
  )
```

``` {r sub-levelAffectChange, eval=F,include=F}
pdf("AffectChangePerPID.pdf", width = 10, height = 4)
cols <- c("pre" = "steelblue", "pst" = "orange")
for (pid in unique(EMA.ERonly$PID)) {
  d <- EMA.ERonly[EMA.ERonly$PID == pid, ]
  pa_vals <- as.vector(rbind(d$PA_pre, d$PA_pst))
  na_vals <- as.vector(rbind(d$NA_pre, d$NA_pst))
  conds <- rep(c("pre", "pst"), nrow(d))
  x <- seq_along(pa_vals)
 par(mfrow = c(1, 2), mar = c(4, 4, 2, 1))
  
  # --- PA ---
  plot(x, pa_vals, pch = 19, col = cols[conds],
       xlab = "Prompt index", ylab = "PA", main = paste("PID", pid, "- PA"),
       xaxt = "n", ylim = range(c(pa_vals, na_vals), na.rm = TRUE))
  for (i in 1:nrow(d)) lines(c(2*i-1, 2*i), c(d$PA_pre[i], d$PA_pst[i]), col = "gray70")
  legend("topleft", legend = names(cols), col = cols, pch = 19, bty = "n")
  
  # --- NA ---
  plot(x, na_vals, pch = 19, col = cols[conds],
       xlab = "Prompt index", ylab = "NA", main = paste("PID", pid, "- NA"),
       xaxt = "n", ylim = range(c(pa_vals, na_vals), na.rm = TRUE))
  for (i in 1:nrow(d)) lines(c(2*i-1, 2*i), c(d$NA_pre[i], d$NA_pst[i]), col = "gray70")
  legend("topleft", legend = names(cols), col = cols, pch = 19, bty = "n")
}

dev.off()

pdf("Pst-Pre_perPID.pdf", width = 10, height = 4)
# pick global y-limits so panels are comparable across PIDs
y_all <- c(EMA.ERonly$PA_change_raw, EMA.ERonly$NA_change_raw)
yl <- range(y_all, na.rm = TRUE)
# (optional) make symmetric around 0 for interpretability
ylim_sym <- max(abs(yl), na.rm = TRUE)
yl <- c(-ylim_sym, ylim_sym)

for (pid in unique(EMA.ERonly$PID)) {
  d <- EMA.ERonly[EMA.ERonly$PID == pid, , drop = FALSE]
  if (!nrow(d)) next
  
  x_pa <- seq_along(d$PA_change_raw)
  x_na <- seq_along(d$NA_change_raw)
  
  par(mfrow = c(1, 2), mar = c(4, 4, 2, 1))
  
  # --- PA change ---
  plot(x_pa, d$PA_change_raw, pch = 19, col = "steelblue",
       xlab = "Prompt index", ylab = "PA (post - pre)",
       main = paste("PID", pid, "- PA change"),
       xaxt = "n", ylim = yl)
  axis(1, at = x_pa, labels = x_pa, cex.axis = 0.8)
  abline(h = 0, lty = 2, col = "gray60")
  # (optional) connect sequential prompts:
  lines(x_pa, d$PA_change_raw, col = adjustcolor("steelblue", 0.7))
  
  # --- NA change ---
  plot(x_na, d$NA_change_raw, pch = 19, col = "tomato",
       xlab = "Prompt index", ylab = "NA (post - pre)",
       main = paste("PID", pid, "- NA change"),
       xaxt = "n", ylim = yl)
  axis(1, at = x_na, labels = x_na, cex.axis = 0.8)
  abline(h = 0, lty = 2, col = "gray60")
  lines(x_na, d$NA_change_raw, col = adjustcolor("tomato", 0.7))
}

dev.off()
```

```{r ERSuccess, eval=T, echo=T, warning=F, message=F, cache=F}
##### RAW SCORE#####
fitPA <- lmer(PA_change_raw ~ 1 + (1 | PID), data = EMA.ERonly) 
model_performance(fitPA) 
icc(fitPA)
#95.4% of variance is explained by within person. 
fitNA <- lmer(NA_change_raw ~ 1 + (1 | PID), data = EMA.ERonly)
model_performance(fitNA) 
icc(fitNA)
# Between person variance is almost non-existent
# Distribution, each dot is one participant's mean NA PA changes pst pre
plot_data <- EMA.ERonly %>%
  distinct(PID, PA_change_raw_pm, NA_change_raw_pm)
plot(plot_data$PA_change_raw_pm, main = "Mean PA Change (between-person)",
     xlab = "Participant", ylab = "PA_change_raw_pm", pch = 19)
plot(plot_data$NA_change_raw_pm, main = "Mean NA Change (between-person)",
     xlab = "Participant", ylab = "NA_change_raw_pm", pch = 19)

##### residual approach: how did the person feel compared to how they are expected to feel given their pre-PA/pre-NA.#####
fit_resid <- lmer(PA_pst ~ PA_pre + (1|PID), data = EMA.ERonly)
EMA.ERonly$PA_resid_change <- resid(fit_resid)
fit_resid <- lmer(NA_pst ~ NA_pre + (1|PID), data = EMA.ERonly)
EMA.ERonly$NA_resid_change <- resid(fit_resid)
# Visualize
ggplot(EMA.ERonly, aes(x = PA_pre, y = PA_pst)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  geom_segment(aes(xend = PA_pre, yend = PA_pst - PA_resid_change),
               alpha = 0.3) +
  labs(x = "Pre-PA", y = "Post-PA",
       title = "Residualized Emotion Regulation Success (PA_resid_change)")
ggplot(EMA.ERonly, aes(x = NA_pre, y = NA_pst)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  geom_segment(aes(xend = NA_pre, yend = NA_pst - NA_resid_change),
               alpha = 0.3) +
  labs(x = "Pre-NA", y = "Post-NA",
       title = "Residualized Emotion Regulation Success (NA_resid_change)")

#Check ICC, variance only explained by within person
fitPA.res <- lmer(PA_resid_change ~ 1 + (1 | PID), data = EMA.ERonly) 
model_performance(fitPA.res) 
icc(fitPA.res)
fitNA.res <- lmer(NA_resid_change ~ 1 + (1 | PID), data = EMA.ERonly)
model_performance(fitNA.res) 

##### residual approach 2: fit residual using centered affect variable: PA_pre_w and NA_pre_w#####
fit_resid_w <- lmer(PA_pst ~ PA_pre_w + (1|PID), data = EMA.ERonly)
EMA.ERonly$PA_resid_change_w <- resid(fit_resid_w)
fit_resid_w <- lmer(NA_pst ~ NA_pre_w + (1|PID), data = EMA.ERonly)
EMA.ERonly$NA_resid_change_w <- resid(fit_resid_w)
# Visualize
ggplot(EMA.ERonly, aes(x = PA_pre_w, y = PA_pst)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  geom_segment(aes(xend = PA_pre_w, yend = PA_pst - PA_resid_change),
               alpha = 0.3) +
  labs(x = "Pre-PA (within)", y = "Post-PA",
       title = "Residualized Emotion Regulation Success (PA_resid_change)")
ggplot(EMA.ERonly, aes(x = NA_pre_w, y = NA_pst)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  geom_segment(aes(xend = NA_pre_w, yend = NA_pst - NA_resid_change),
               alpha = 0.3) +
  labs(x = "Pre-NA (within)", y = "Post-NA",
       title = "Residualized Emotion Regulation Success (NA_resid_change)")

#Check ICC, variance only explained by within person
fitPA.res.w <- lmer(PA_resid_change_w ~ 1 + (1 | PID), data = EMA.ERonly) 
model_performance(fitPA.res.w) 
fitNA.res.w <- lmer(NA_resid_change_w ~ 1 + (1 | PID), data = EMA.ERonly)
model_performance(fitNA.res.w) 

#####SELF REPORTED PERCEIVED SUCCESS#####
# ICC 0.46 for perceived success looks regular
fitSuccess <- lmer(perceived_success ~ 1 + (1 | PID), data = EMA.ERonly)
model_performance(fitSuccess)
# Only within-person variation in perceived success is associated with PA residual changes. 
summary(lmer(data = EMA.ERonly, PA_resid_change_w~perceived_success_w + perceived_success_b + (1 | PID)))
# Only within-person variation in perceived success is associated with NA residual changes. 
summary(lmer(data = EMA.ERonly, NA_resid_change_w~perceived_success_w + perceived_success_b + (1 | PID)))
```

```{r inertia, eval=T, echo=T, warning=T, message=T, cache=F}
#####Set shift & Inertia#####
describe(trait.level$shift_score) #Considered centering shift score (gmc)
#If we are looking at between person PA, then compute within subset
#We expect that people with better cognitive flexibility will show less inertia when they are regulating their emotions
m.PA.SS.fluctuation.ER<- lmer(PA_pst ~ PA_pre_w * shift_gmc + Group + (1 + PA_pre_w|PID), data = EMA.ERonly)
summary(m.PA.SS.fluctuation.ER) #When ER is initiated, people with greater cognitive flexibility show less PA inertia
m.NA.SS.fluctuation.ER<- lmer(NA_pst ~ NA_pre_w * shift_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.ERonly)
summary(m.NA.SS.fluctuation.ER) 

m.PA.SS.fluctuation.all<- lmer(PA_pst ~ PA_pre_w * shift_gmc * ER_yes + Group+ (1 + PA_pre_w|PID), data = EMA.all)
summary(m.PA.SS.fluctuation.all) 
m.NA.SS.fluctuation.all<- lmer(NA_pst ~ NA_pre_w * shift_gmc * ER_yes + Group+ (1 + NA_pre_w|PID), data = EMA.all)
summary(m.NA.SS.fluctuation.all) 
#check demo just for this analysis
unique(m.PA.SS.fluctuation.all@frame$PID)
m.PA.SS.fluctuation.all@frame %>%
  distinct(PID, Group) %>%
  count(Group)

m.PA.SS.fluctuation.noER<- lmer(PA_pst ~ PA_pre_w * shift_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.NoER)
summary(m.PA.SS.fluctuation.noER) 
m.NA.SS.fluctuation.noER<- lmer(NA_pst ~ NA_pre_w * shift_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.NoER)
summary(m.NA.SS.fluctuation.noER) 

sd_shift <- sd(trait.level$shift_gmc, na.rm = TRUE)
shift_lvls <- c("Low set shift (-1 SD)", "Mean set shift", "High set shift (+1 SD)")
cols3 <- setNames(piratepal("pony")[c(1,5,8)], shift_lvls)
ef <- effects::effect("PA_pre_w*shift_gmc*ER_yes", 
             mod = m.PA.SS.fluctuation.all, 
             xlevels = list(shift_gmc = c(-sd_shift, 0, sd_shift),
                                     ER_yes = c(0, 1)))
efdata <- as.data.frame(ef)
efdata$ER_yes <- factor(efdata$ER_yes, levels = c(0,1), labels = c("No Regulation", "Regulation"))
efdata$shift_gmc <-  factor(efdata$shift_gmc, levels = c(-sd_shift, 0, sd_shift), labels = shift_lvls)
fig1<- ggplot(efdata, aes(x = PA_pre_w, y = fit, color = shift_gmc, group = shift_gmc)) + 
  geom_line(size = 1.2) +
  geom_ribbon(aes(ymin = fit - se, ymax = fit + se, fill = shift_gmc), alpha = 0.3) + 
  facet_wrap(~ ER_yes) +
  scale_color_manual(values = cols3, breaks = shift_lvls, drop = FALSE,
                     aesthetics = c("colour","fill")) +
  labs(x = "PA_pre_w", y = "PA_post", color = "Set shift score", fill = "Set shift score") +
  theme_classic() +
  theme(panel.spacing = unit(3, "lines"))

ef <- effects::effect("NA_pre_w*shift_gmc*ER_yes", 
             mod = m.NA.SS.fluctuation.all, 
             xlevels = list(shift_gmc = c(-sd_shift, 0, sd_shift),
                                     ER_yes = c(0, 1)))
efdata <- as.data.frame(ef)
efdata$ER_yes <- factor(efdata$ER_yes, levels = c(0,1), labels = c("No Regulation", "Regulation"))
efdata$shift_gmc <-  factor(efdata$shift_gmc, levels = c(-sd_shift, 0, sd_shift), labels = shift_lvls)
fig2 <- ggplot(efdata, aes(x = NA_pre_w, y = fit, color = shift_gmc, group = shift_gmc)) + 
  geom_line(size = 1.2) +
  geom_ribbon(aes(ymin = fit - se, ymax = fit + se, fill = shift_gmc), alpha = 0.3) + 
  facet_wrap(~ ER_yes) +
  scale_color_manual(values = cols3, breaks = shift_lvls, drop = FALSE,
                     aesthetics = c("colour","fill")) +
  labs(x = "NA_pre_w", y = "NA_post", color = "Set shift score", fill = "Set shift score") +
  theme_classic() +
  theme(panel.spacing = unit(3, "lines"))



fig1;fig2
#Nback
m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * nback_gmc + Group + (1 + PA_pre_w|PID), data = EMA.ERonly)
summary(m.PA.SS.fluctuation) 
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * nback_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.ERonly)
summary(m.NA.SS.fluctuation) 
m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * nback_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.all)
summary(m.PA.SS.fluctuation) 
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * nback_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.all)
summary(m.NA.SS.fluctuation) 
m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * nback_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.NoER)
summary(m.PA.SS.fluctuation) 
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * nback_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.NoER)
summary(m.NA.SS.fluctuation) # Sig, higher nback, more NA inertia when not regulating

#PGNG PCI
m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * PCI_gmc + Group + (1 + PA_pre_w|PID), data = EMA.ERonly)
summary(m.PA.SS.fluctuation) 
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * PCI_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.ERonly)
summary(m.NA.SS.fluctuation) 

m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * PCI_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.all)
summary(m.PA.SS.fluctuation)
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * PCI_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.all)
summary(m.NA.SS.fluctuation)

m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * PCI_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.NoER)
summary(m.PA.SS.fluctuation)
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * PCI_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.NoER)
summary(m.NA.SS.fluctuation) 

#PGNG RT
m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * RT_gmc + Group + (1 + PA_pre_w|PID), data = EMA.ERonly)
summary(m.PA.SS.fluctuation) 
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * RT_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.ERonly)
summary(m.NA.SS.fluctuation) #sig

m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * RT_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.all)
summary(m.PA.SS.fluctuation)
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * RT_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.all)
summary(m.NA.SS.fluctuation) # sig

m.PA.SS.fluctuation<- lmer(PA_pst ~ PA_pre_w * RT_gmc + Group+ (1 + PA_pre_w|PID), data = EMA.NoER)
summary(m.PA.SS.fluctuation) 
m.NA.SS.fluctuation<- lmer(NA_pst ~ NA_pre_w * RT_gmc + Group+ (1 + NA_pre_w|PID), data = EMA.NoER)
summary(m.NA.SS.fluctuation) 
```


```{r variability, eval=T, echo=T, warning=F, message=F, cache=F}
summary(lm(data = trait.level, NA_mean_merged~Group)) #rMDD is associated with higher mean NA
summary(lm(data = trait.level, PA_mean_merged~Group)) #rMDD is associated with lower mean PA
#####affect variability across all surveys
summary(lm(data = trait.level, NA_sd_merged~Group)) #rMDD is associated with higher instability of NA
summary(lm(data = trait.level, PA_sd_merged~Group)) #rMDD is associated with higher instability of PA
m.NA <- lm(data = trait.level, NA_sd_merged~Group+NA_b+Site) #rMDD is still marginally associated with higher instability of NA, accounting for mean level of NA
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, PA_sd_merged~Group+PA_b+Site) #rMDD is significantly associated with higher instability of PA, accounting for mean level of PA
summary(m.PA)
vif(m.PA)
#look at whether pre & merge correlate with each other; merged affect variability strongly correlate with both pre and pst sd
cor(trait.level$NA_sd_merged, trait.level$NA_sd_pre, use = "complete.obs")
cor(trait.level$NA_sd_merged, trait.level$NA_sd_pst, use = "complete.obs")
cor(trait.level$PA_sd_merged, trait.level$PA_sd_pre, use = "complete.obs")
cor(trait.level$PA_sd_merged, trait.level$PA_sd_pst, use = "complete.obs")
# I also wanna check cor between NA and affect variability
cor(trait.level$NA_sd_merged, trait.level$NA_b, use = "complete.obs") #0.73
cor(trait.level$PA_sd_merged, trait.level$PA_b, use = "complete.obs") #-0.43
```

```{r instability, eval=T, echo=T, warning=F, message=F, cache=F}
summary(lm(data = trait.level, RMSSD_NA~Group)) #rMDD is associated with higher NA instability
summary(lm(data = trait.level, RMSSD_PA~Group)) #rMDD is associated with higher PA instability
m.NA <- lm(data = trait.level, RMSSD_NA~Group+NA_b+Site) #rMDD is significantly associated with higher instability of NA, accounting for between-person mean level of NA
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, RMSSD_PA~Group+PA_b+Site) #rMDD is significantly associated with higher instability of PA, accounting for between-person mean level of PA
summary(m.PA)
vif(m.PA)
```

```{r variability and psychopathology, eval=T, echo=T, warning=F, message=F, cache=F}
#BDI-II: bdi_score
#Beck Suicide Scale: bss_sisum; probably not worth looking at since there's not much variance
#PSWQ: pswq_total
#emotionrelated_impulsivity_eri: Positive Urgency: eri_pu_total; Reflexive Reactions to Feelings: eri_rrf_total; Feelings Trigger Action Factor: eri_ftaf_total; Generalization:eri_gen_total ; Emotions Color Worldview:eri_ecw_total
#HAM-A: ham_a_score
#HAM-D: hamd_sf_total
vars <- c("bdi_score", 
          "pswq_total",
          "eri_pu_total", "eri_rrf_total", "eri_ftaf_total", "eri_gen_total", "eri_ecw_total",
          "ham_a_score",
          "hamd_sf_total")
labels <- c("BDI-II Total",
            "PSWQ Total (Worry)",
            "ERI Positive Urgency", "ERI Reflexive Reactions to Feelings", "ERI Feelings Trigger Action", "ERI Generalization","ERI Emotions Color Worldview",
            "HAM-A (Anxiety)",
            "HAM-D (Depression)")
describe(redcap.v1[vars])
for (i in 1:length(vars)) {
  v <- vars[i]
  label <- labels[i]
    d <- density(redcap.v1[[v]], na.rm = TRUE)
    plot(d,
         main = paste("Density of", label),
         xlab = label,
         ylab = "Density",
         col = "darkblue",
         lwd = 2)
    polygon(d, col = adjustcolor("skyblue", alpha.f = 0.4), border = NA)
}

m.NA <- lm(data = trait.level, bdi_score~NA_sd_merged+NA_b+Group)
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, bdi_score~PA_sd_merged+PA_b+Group)
summary(m.PA)
vif(m.PA)
m.NA <- lm(data = trait.level, pswq_total~NA_sd_merged+NA_b+Group)
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, pswq_total~PA_sd_merged+PA_b+Group)
summary(m.PA)
vif(m.PA)
m.NA <- lm(data = trait.level, ham_a_score~NA_sd_merged+NA_b+Group)
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, ham_a_score~PA_sd_merged+PA_b+Group)
summary(m.PA)
vif(m.PA)
m.NA <- lm(data = trait.level, hamd_sf_total~NA_sd_merged+NA_b+Group)
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, hamd_sf_total~PA_sd_merged+PA_b+Group)
summary(m.PA)
vif(m.PA)
m.NA <- lm(data = trait.level, eri_gen_total~NA_sd_merged+NA_b+Group)
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, eri_gen_total~PA_sd_merged+PA_b+Group)
summary(m.PA)
vif(m.PA)
m.NA <- lm(data = trait.level, eri_ecw_total~NA_sd_merged+NA_b+Group)
summary(m.NA)
vif(m.NA)
m.PA <- lm(data = trait.level, eri_ecw_total~PA_sd_merged+PA_b+Group)
summary(m.PA)
vif(m.PA)

m.PA <- lm(data = trait.level, PA_sd_merged~flanker_score+PA_b+Group)
summary(m.PA)
vif(m.PA)
m.NA <- lm(data = trait.level, NA_sd_merged~flanker_score+NA_b+Group)
summary(m.NA)
vif(m.NA)

#####future#####
m.NA <- lm(data = trait.level, bdi_followup~bdi_score*NA_sd_merged+NA_b+Group)
summary(m.NA)
m.PA <- lm(data = trait.level, bdi_followup~bdi_score*PA_sd_merged+PA_b+Group)
summary(m.PA)
m.NA <- lm(data = trait.level, bdi_followup~bdi_score*RMSSD_NA+NA_b+Group)
summary(m.NA)
m.PA <- lm(data = trait.level, bdi_followup~bdi_score*RMSSD_PA+PA_b+Group)
summary(m.PA)  
```
